version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=password
    ports:
      - "9000:9000"
    networks:
      - matchoracle

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - matchoracle

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - matchoracle

  predictor:
    build:
      context: ./predictor
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - matchoracle

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - matchoracle

networks:
  matchoracle:

volumes:
  db_data:
